
services:
  api:
    build: ./services/api
    container_name: api
    command: >
      gunicorn -k uvicorn.workers.UvicornWorker main:app
      --bind 0.0.0.0:8000
      --workers ${API_WORKERS}
      --timeout ${API_TIMEOUT}
    environment:
      - API_WORKERS=${API_WORKERS}
      - API_TIMEOUT=${API_TIMEOUT}
      - EMBEDDER_HOST=${EMBEDDINGS_HOST}
      - EMBEDDER_PORT=${EMBEDDINGS_PORT}
      - ATTRIBUTES_HOST=${ATTRIBUTES_HOST}
      - ATTRIBUTES_PORT=${ATTRIBUTES_PORT}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      - embeddings
      - attributes
      - qdrant
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  embeddings:
    build: ./services/embeddings
    container_name: embeddings
    command: ["python", "grpc_server.py", "--port", "${EMBEDDINGS_GRPC_PORT}"]
    environment:
      - MODEL_URL=${EMBEDDINGS_MODEL_URL}
      - MODEL_PATH=${EMBEDDINGS_MODEL_PATH}
      - GRPC_PORT=${EMBEDDINGS_GRPC_PORT}
      - GRPC_MAX_WORKERS=${GRPC_MAX_WORKERS}
      - GRPC_MAX_MESSAGE_LENGTH=${GRPC_MAX_MESSAGE_LENGTH}
      - ONNX_PROVIDERS=${ONNX_PROVIDERS}
      - ONNX_INTRA_OP_THREADS=${ONNX_INTRA_OP_THREADS}
      - ONNX_INTER_OP_THREADS=${ONNX_INTER_OP_THREADS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:${EMBEDDINGS_GRPC_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3

  attributes:
    build: ./services/face-attributes
    container_name: attributes
    command: ["python", "grpc_server.py", "--port", "${ATTRIBUTES_GRPC_PORT}"]
    environment:
      - MODEL_URL=${ATTRIBUTES_MODEL_URL}
      - MODEL_PATH=${ATTRIBUTES_MODEL_PATH}
      - GRPC_PORT=${ATTRIBUTES_GRPC_PORT}
      - GRPC_MAX_WORKERS=${GRPC_MAX_WORKERS}
      - GRPC_MAX_MESSAGE_LENGTH=${GRPC_MAX_MESSAGE_LENGTH}
      - ONNX_PROVIDERS=${ONNX_PROVIDERS}
      - ONNX_INTRA_OP_THREADS=${ONNX_INTRA_OP_THREADS}
      - ONNX_INTER_OP_THREADS=${ONNX_INTER_OP_THREADS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:${ATTRIBUTES_GRPC_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage

    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  qdrant_data:
