# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face-attributes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'face-attributes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66\x61\x63\x65-attributes.proto\x12\x0e\x66\x61\x63\x65\x61ttributes\"&\n\x10\x41ttributeRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\xd0\x03\n\x11\x41ttributeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0c\n\x04race\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\x44\n\nrace_probs\x18\x06 \x03(\x0b\x32\x30.faceattributes.AttributeResponse.RaceProbsEntry\x12H\n\x0cgender_probs\x18\x07 \x03(\x0b\x32\x32.faceattributes.AttributeResponse.GenderProbsEntry\x12\x42\n\tage_probs\x18\x08 \x03(\x0b\x32/.faceattributes.AttributeResponse.AgeProbsEntry\x1a\x30\n\x0eRaceProbsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x32\n\x10GenderProbsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a/\n\rAgeProbsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32h\n\x10\x41ttributeService\x12T\n\rGetAttributes\x12 .faceattributes.AttributeRequest\x1a!.faceattributes.AttributeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_attributes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTRIBUTERESPONSE_RACEPROBSENTRY']._loaded_options = None
  _globals['_ATTRIBUTERESPONSE_RACEPROBSENTRY']._serialized_options = b'8\001'
  _globals['_ATTRIBUTERESPONSE_GENDERPROBSENTRY']._loaded_options = None
  _globals['_ATTRIBUTERESPONSE_GENDERPROBSENTRY']._serialized_options = b'8\001'
  _globals['_ATTRIBUTERESPONSE_AGEPROBSENTRY']._loaded_options = None
  _globals['_ATTRIBUTERESPONSE_AGEPROBSENTRY']._serialized_options = b'8\001'
  _globals['_ATTRIBUTEREQUEST']._serialized_start=41
  _globals['_ATTRIBUTEREQUEST']._serialized_end=79
  _globals['_ATTRIBUTERESPONSE']._serialized_start=82
  _globals['_ATTRIBUTERESPONSE']._serialized_end=546
  _globals['_ATTRIBUTERESPONSE_RACEPROBSENTRY']._serialized_start=397
  _globals['_ATTRIBUTERESPONSE_RACEPROBSENTRY']._serialized_end=445
  _globals['_ATTRIBUTERESPONSE_GENDERPROBSENTRY']._serialized_start=447
  _globals['_ATTRIBUTERESPONSE_GENDERPROBSENTRY']._serialized_end=497
  _globals['_ATTRIBUTERESPONSE_AGEPROBSENTRY']._serialized_start=499
  _globals['_ATTRIBUTERESPONSE_AGEPROBSENTRY']._serialized_end=546
  _globals['_ATTRIBUTESERVICE']._serialized_start=548
  _globals['_ATTRIBUTESERVICE']._serialized_end=652
# @@protoc_insertion_point(module_scope)
