# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embeddings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embeddings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65mbeddings.proto\x12\nembeddings\"&\n\x10\x45mbeddingRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"6\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x0e\n\x06status\x18\x02 \x01(\t2_\n\x10\x45mbeddingService\x12K\n\x0cGetEmbedding\x12\x1c.embeddings.EmbeddingRequest\x1a\x1d.embeddings.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=32
  _globals['_EMBEDDINGREQUEST']._serialized_end=70
  _globals['_EMBEDDINGRESPONSE']._serialized_start=72
  _globals['_EMBEDDINGRESPONSE']._serialized_end=126
  _globals['_EMBEDDINGSERVICE']._serialized_start=128
  _globals['_EMBEDDINGSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
